#!/usr/bin/env zsh

## USAGE
# ./run 2022 7
nodemon --exec "gcc -Wall -O3 ./$1/$2/main.c -lm -o ./$1/$2/main.out && /usr/bin/time -f \"Time [h]:mm:ss %e\nMax memory %M KB\" ./$1/$2/main.out" --watch ./$1/$2/main.c
